// <auto-generated />
using System;
using DeveloperEvaluation.CartsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperEvaluation.CartsApi.Migrations
{
    [DbContext(typeof(CartsDBContext))]
    partial class CartsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperEvaluation.CartsApi.Models.Carts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("DateOfSale")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataVenda");

                    b.Property<int>("StatusCartsEn")
                        .HasColumnType("integer")
                        .HasColumnName("StatusCarrinho");

                    b.Property<Guid>("UserIdInsert")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioInsert");

                    b.HasKey("Id");

                    b.ToTable("Carrinho", (string)null);
                });

            modelBuilder.Entity("DeveloperEvaluation.CartsApi.Models.CartsItens", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CartsId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Discounts")
                        .HasPrecision(20, 5)
                        .HasColumnType("numeric(20,5)")
                        .HasColumnName("Desconto");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantidade");

                    b.Property<decimal>("UnitPrices")
                        .HasPrecision(20, 5)
                        .HasColumnType("numeric(20,5)")
                        .HasColumnName("PrecoUnitario");

                    b.HasKey("Id");

                    b.HasIndex("CartsId");

                    b.HasIndex("ProductId");

                    b.ToTable("CarrinhoItens", (string)null);
                });

            modelBuilder.Entity("DeveloperEvaluation.CartsApi.Models.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Image")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Imagem");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 5)
                        .HasColumnType("numeric(20,5)")
                        .HasColumnName("Valor");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("ProdutosCarrinho", (string)null);
                });

            modelBuilder.Entity("DeveloperEvaluation.CartsApi.Models.CartsItens", b =>
                {
                    b.HasOne("DeveloperEvaluation.CartsApi.Models.Carts", "Carts")
                        .WithMany("CartsItens")
                        .HasForeignKey("CartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeveloperEvaluation.CartsApi.Models.Products", "Product")
                        .WithMany("CartsItens")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carts");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DeveloperEvaluation.CartsApi.Models.Products", b =>
                {
                    b.OwnsOne("DeveloperEvaluation.CartsApi.ValueObjects.RattingValueObjects", "Ratting", b1 =>
                        {
                            b1.Property<Guid>("ProductsId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int?>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("Contador");

                            b1.Property<decimal?>("Rate")
                                .HasPrecision(20, 5)
                                .HasColumnType("numeric(20,5)")
                                .HasColumnName("Rate");

                            b1.HasKey("ProductsId");

                            b1.ToTable("ProdutosCarrinho");

                            b1.WithOwner()
                                .HasForeignKey("ProductsId");
                        });

                    b.Navigation("Ratting")
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperEvaluation.CartsApi.Models.Carts", b =>
                {
                    b.Navigation("CartsItens");
                });

            modelBuilder.Entity("DeveloperEvaluation.CartsApi.Models.Products", b =>
                {
                    b.Navigation("CartsItens");
                });
#pragma warning restore 612, 618
        }
    }
}
